[general]
import = ["~/.config/alacritty/theme.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12

[window]
padding = { x = 10, y = 10 }
decorations = "None"

[env]
TERM = "xterm-256color"

